version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (net.Listener).Close
      - (*net.TCPListener).Close
      - fmt.Fprintf
      - fmt.Fprintln
    check-type-assertions: false

  staticcheck:
    checks:
      - "all"
      - "-QF*"

  govet:
    disable:
      - hostport
